config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #admin側
  namespace :admin do
    get '/' => 'genres#index'
    # get 'about' => 'homes#about'
    resources :genres
  end

  #user側
  root to: 'homes#top'
  get '/' => 'homes#top'
  get 'about' => 'homes#about'

  resources :users, only: [:show, :edit, :update]
  get "user/:id/unsubscribe" => "users#unsubscribe", as: 'user_unsubscribe'
  patch 'user/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'

  resources :rooms, only: [:index, :create, :show]
  resources :genres
  resources :pets do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "search" => "pets#search"

  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :pet_images, dependent: :destroy
  accepts_attachments_for :pet_images, attachment: :image

  validates :birthday, presence: true
  validates :gender, presence: true
  validates :introduction, length: { maximum: 200 }
  validates :age, presence: true
  # validates :pet_images, presence: true
  validates :prefecture_id, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum gender: { 男の子♂: 0, 女の子♀: 1 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # here
  scope :search, -> (search_params) do # scopeでsearchメソッドを定義。(search_params)は引数
    return if search_params.blank? # 検索フォームに値がなければ以下の手順は行わない

    # prefecture(search_params[:prefecture])
    birthday_from(search_params[:birthday_from]).
      birthday_to(search_params[:birthday_to]).
      prefecture_id_is(search_params[:prefecture_id]).
      gender_is(search_params[:gender]).
      genre_id_is(search_params[:genre_id])
    # 下記で定義しているscopeメソッドの呼び出し。「.」で繋げている
  end

  # scopeを定義。
  scope :birthday_from, -> (from) { where('? <= birthday', from) if from.present? }
  scope :birthday_to, -> (to) { where('birthday <= ?', to) if to.present? }
  scope :prefecture_id_is, -> (prefecture_id) { where(prefecture_id: prefecture_id) if prefecture_id.present? }
  scope :gender_is, -> (gender) { where(gender: gender) if gender.present? }
  scope :genre_id_is, -> (genre_id) { where(genre_id: genre_id) if genre_id.present? }

  # scope :メソッド名 -> (引数) { SQL文 }
  # end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @pet = Pet.new
    @genres = Genre.all
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    if @pet.save
      redirect_to pets_path, notice: '投稿に成功しました。'
    else
      @genres = Genre.all
      render :new
    end
  end

  def index
    @genres = Genre.all
    @pets = Pet.page(params[:page]).reverse_order.where(:is_active => true)
    @search_params = pet_search_params  # 検索結果の画面で、フォームに検索した値を表示するために、paramsの値をビューで使えるようにする
  end

  def show
    @pets = Pet.all
    @pet = Pet.find(params[:id])
    @user = current_user
    @comment = Comment.new
    @comments = Comment.all
  end

  def edit
    @pet = Pet.find(params[:id])
    @genres = Genre.all
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path, notice: '変更内容を更新しました。'
    else
      @genres = Genre.all
      render :edit
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path, notice: '投稿内容を削除しました。'
  end

  def search
    @search_params = pet_search_params  # 検索結果の画面で、フォームに検索した値を表示するために、paramsの値をビューで使えるようにする
    @pets = Pet.where(:is_active => true).search(@search_params).includes(:genre).page(params[:page]).per(4)
    # Reservationモデルのsearchを呼び出し、引数としてparamsを渡している。
  end

  private

  def pet_search_params
    params.fetch(:search, {}).permit(
      :prefecture_id, :birthday_from, :birthday_to, :gender, :genre_id
    )
    # fetch(:search, {})と記述することで、検索フォームに値がない場合はnilを返し、エラーが起こらなくなる
    # ここでの:searchには、フォームから送られてくるparamsの値が入っている
  end

  # private

  def ensure_correct_user
    @pet = Pet.find(params[:id])
    unless @pet.user == current_user
      redirect_to pets_path
    end
  end

  def pet_params
    params.require(:pet).permit(
      :name, :birthday, :gender, :introduction,
      :genre_id, :prefecture_id, :age, :is_active,
      :image, pet_images_images: []
    )
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_search.html.erb
<div class="search-bar">
  <h5 class="fas fa-search">条件で検索</h5>
  <%= form_with(scope: :search, url: search_path, method: :get, local: true) do |f| %>
    <div class="field">
      <%= f.label :birthday, "お誕生日" %>
      <%= f.date_field :birthday_from, value: search_params[:birthday_from] %> ~
      <%= f.date_field :birthday_to, value: search_params[:birthday_to] %>
    </div><br>
  
    <div class="field">
      <%= f.label :prefecture_id, "都道府県" %><br>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, selected: search_params[:prefecture_id], prompt: "----") %>
    </div><br>
    
    <div class="field">
      <%= f.label :"性別" %><br>
      <%= f.radio_button :gender, :男の子♂ %>
      <%= f.label :"男の子♂" %><br>
      <%= f.radio_button :gender, :女の子♀ %>
      <%= f.label :"女の子♀"%>
    </div><br>
  
    <div class="field">
      <%= f.label :"ジャンル" %><br>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, selected: search_params[:genre_id], prompt: "----") %>
    </div><br>
    <%= submit_tag '検索', class: "btn btn-outline-secondary btn-block" %>
  <% end %>
</div>

app/views/pets/_user.html.erb
<div class="side-bar">
<h2 class="heading-user">

</h2>
<table class='table table-borderless user-info'>
  <thead>
    <tbody>
        <tr></tr>
        <tr>
          <th><%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, size: '100x100', fallback: "no_image_icon.jpg", class: "rounded-circle" %>
          <p><%= user.full_name %></p>
          <% end %></th>
        </tr>
        <tr>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th><%= link_to followings_user_path(user.id) do %>
                <p>フォロー<%= user.followings.count %></p>
              <% end %></th>
        </tr>
        <tr>
          <th><%= link_to followers_user_path(user.id) do %>
                <p>フォロワー<%= user.followers.count %></p>
              <% end %></th>
        </tr>
    </tbody>
  </thead>
</table>
<div id="follow_button">
  <%= render 'relationships/follow_button', user: user %>
</div>
</br>
<% if @user == current_user %>
  <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  <br><br>
  <%= link_to "", rooms_path, class: "btn btn-outline-secondary btn-block fas fa-comments" %>
<% end %>
<% unless user.id == current_user.id %>
  <% if @is_room == true %>
    <%= link_to "DMを送る", room_path(@room_id), class: "btn btn-outline-secondary btn-block" %>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class: "btn btn-secondary btn-block" %>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/pets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-sm-12 text-center mt-4">
      <div class="background">
        <h2 class="heading">投稿内容編集</h2>
        <%= render 'layouts/error_messages', model: @pet %>
        <%= form_with model: @pet, url: pet_path, method: :put, local: true do |f| %>

          <%= link_to pet_path(@pet.id) do %>
              <% @pet.pet_images.first(1).each do |image| %>
                <%= attachment_image_tag image, :image, size: '350x300', class: "rounded" %>
              <% end %>
          <% end %>
          <table class="table table-borderless">
            <tr>
              <td></td>
            </tr>
            <tr>
              <td><%= f.label :"写真" %></td>
              <td><%= f.attachment_field :pet_images_images, multiple: true %></td>
            </tr>
            <tr>
              <td><%= f.label :"お名前" %></td>
              <td><%= f.text_field :name, class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label :"ジャンル" %></td>
              <td><%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "-- 選択してください--") %></td>
            </tr>
            <tr>
              <td><%= f.label :"お誕生日" %></td>
              <td><%= f.text_field :birthday, class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label :"年齢" %></td>
              <td><%= f.text_field :age, class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label :"性別" %></td>
              <td><%= f.radio_button :gender,"男の子♂" %>男の子(♂)<span></span>
                  <%= f.radio_button :gender, "女の子♀" %>女の子(♀)</td>
            </tr>
            <tr>
              <td><%= f.label :"都道府県" %></td>
              <td><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "-- 選択してください--" %></td>
              </tr>
            <tr>
              <td><%= f.label :"紹介" %></td>
              <td><%= f.text_area :introduction, class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label :"ステータス" %></td>
              <td><%= f.select :is_active, [['募集中', true], ['新しいおうちが見つかったよ！', false]], prompt: "-- 選択してください --"  %></td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "更新する", class: "btn btn-secondary" %></td>
              <td><%= link_to "削除する", pet_path(@pet), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %></td>
            </tr>
            <tr>
              <td></td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class='container'>
  <div class='row mt-5'>
    <div class="col-lg-2">
      <%= render 'pets/search', search_params: @search_params %>
    </div>
    <div class="col-lg-9 offset-lg-1">
      <p id="notice"><%=  notice %></p>
      <div class="background">
        <h2 class="heading"><i class="far fa-star"></i>  飼い主さんを募集中  <i class="far fa-star"></i></h2>
        <div class="pet-box">
          <% @pets.each do |pet| %>
            <div class="pet-list">
              <%= link_to pet_path(pet.id) do %>
                <% pet.pet_images.first(1).each do |image| %>
                  <%= attachment_image_tag image, :image, size: '200x200', class: "rounded" %>
                <% end %>
              <% end %>
              <p class="pet-name">お名前: <%= pet.name %></p>
              <p>生年月日: <%= pet.birthday %></p>
              <p>年齢: <%= pet.age %></p>
              <p>性別: <%= pet.gender %></p>
              <p>都道府県: <%= pet.prefecture.name %></p>
              <p>投稿者:
                <%= attachment_image_tag pet.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image_icon.jpg",class: "rounded-circle" %>
              </p>

              <% if user_signed_in? %>
              <div class="favorite-btn<%= pet.id %>">
                <%= render 'favorites/favorite', pet: pet %>
              </div>
              <p>コメント件数：<%= pet.comments.count %></p>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= paginate @pets %>
      </div>
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-2">
      <%= render 'pets/user', user: current_user %>
    </div>
    <div class="col-lg-9 offset-lg-1">
      <h2 class="heading">飼い主さんを募集する</h2>
      <%= render 'layouts/error_messages', model: @pet %>

      <%= form_with model: @pet, url: pets_path, method: :post, local: true do |f| %>
        <table class="table table-borderless">
          <tr>
            <td><%= f.label :"写真" %></td>
            <td><%= f.attachment_field :pet_images_images, multiple: true %></td>
          </tr>
          <tr>
            <td><%= f.label :"お名前" %></td>
            <td><%= f.text_field :name, class: "form-control" %></td>
          </tr>
          <tr>
            <td><%= f.label :"ジャンル" %></td>
            <td><%= f.collection_select(:genre_id, Genre.where(:is_active => true), :id, :name, prompt: "-- 選択してください--") %></td>
          </tr>
          <tr>
            <td><%= f.label :"生年月日" %></td>
            <td><%= f.text_field :birthday, class: "form-control" %></td>
          </tr>
          <tr>
            <td><%= f.label :"年齢" %></td>
            <td><%= f.text_field :age, class: "form-control" %></td>
          </tr>
          <tr>
            <td><%= f.label :"性別" %></td>
            <td><%= f.radio_button :gender, :男の子♂ %>
                <%= f.label :"男の子♂" %>
                <%= f.radio_button :gender, :女の子♀ %>
                <%= f.label :"女の子♀"%></td>
          </tr>
          <tr>
            <td><%= f.label :"都道府県" %></td>
            <td><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "-- 選択してください--" %></td>
          </tr>
          <tr>
            <td><%= f.label :"紹介" %></td>
            <td><%= f.text_area :introduction, class: "form-control" %></td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit "投稿する", class: "btn btn-secondary" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/search.html.erb
<div class='container'>
  <div class="row mt-5">
    <div class="col-lg-12">
      <div class="background">
        <h2 class="heading">検索結果</h2>
          <div class="pet-box">
          <% unless @search_params.blank? %>
            <% @pets.each do |pet| %>  
            <div class="pet-list">
              <%= link_to pet_path(pet.id) do %>
                <% pet.pet_images.first(1).each do |image| %>
                  <%= attachment_image_tag image, :image, size: '200x200', class: "rounded" %>
                <% end %>
              <% end %>
            
              <p class="pet-name">お名前: <%= pet.name %></p>
              <p>お誕生日: <%= pet.birthday %></p>
              <p>年齢: <%= pet.age %></p>
              <p>性別: <%= pet.gender %></p>
              <p>都道府県: <%= pet.prefecture.name %></p>
              <p>ステータス：
                <% if pet.is_active == true %>
                  <td>募集中</td>
                <% elsif pet.is_active == false %>
                  <td>新しいおうちが見つかったよ！</td>
                <% end %></p>
              <p>投稿者:
                <%= attachment_image_tag pet.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image_icon.jpg",class: "rounded-circle" %>
              </p>
            
              <% if user_signed_in? %>
                <div class="favorite-btn<%= pet.id %>">
                  <%= render 'favorites/favorite', pet: pet %>
                </div>
                <p>コメント件数：<%= pet.comments.count %></p>
              <% end %>
            </div>
            <% end %>
          <% end %>
        </div>
        <%= paginate @pets %>
      </div>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <p id="notice"><%=  notice %></p>
      <h2 class="heading">ペット詳細</h2>
      <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
      <div id="slider">
          <% @pet.pet_images.each do |image| %>
            <%= attachment_image_tag image, :image, format: "jpeg", size: '540x359' %>
          <% end %>
      </div>
      <% if user_signed_in? %>
      <div class="comments">
        <div class="comments_<%= @pet.id %>">
          <%= render 'comments/comment', pet: @pet, comment: @comment %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="col-lg-5 mt-5">
      <table class="table table-borderless mt-5">
        <thead>
          <tr>
            <th>ジャンル:</th>
            <th><%= @pet.genre.name %></th>
          </tr>
          <tr>
            <th>お名前:</th>
            <th><%= @pet.name %></th>
          </tr>
          <tr>
            <th>生年月日: </th>
            <th><%= @pet.birthday %></th>
          </tr>
          <tr>
            <th>年齢: </th>
            <th><%= @pet.age %>才</th>
          </tr>
          <tr>
            <th>性別:</th>
            <th><%= @pet.gender %></th>
          </tr>
          <tr>
            <th>都道府県:</th>
            <th><%= @pet.prefecture.name %></th>
          </tr>
          <tr>
            <th>特徴:</th>
            <th><%= @pet.introduction %></th>
          </tr>
          <tr>
            <th>ステータス:</th>
            <th><% if @pet.is_active == true %>
                  飼い主さん募集中
                <% elsif @pet.is_active == false %>
                  新しいおうちが見つかったよ！
                <% end %></th>
          </tr>
          <tr>
            <th>投稿者:</th>
            <th><% if user_signed_in? %>
                  <%= link_to user_path(@pet.user) do %>
                    <%= attachment_image_tag @pet.user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image_icon.jpg", class: "rounded-circle" %>
                  <% end %>
                <% else %>
                  <%= attachment_image_tag @pet.user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image_icon.jpg", class: "rounded-circle" %>
                <% end %></th>
          </tr>
          <% if user_signed_in? %>
          <tr>
            <th>検討したい！</th>
            <th class="favorite-btn<%= @pet.id %>">
              <%= render 'favorites/favorite', pet: @pet %></th>
          </tr>
          <% end %>
          <tr>
            <th></th>
          </tr>
          <tr>
            <th></th>
            <th><% if @pet.user == current_user %>
                  <%= link_to "編集する", edit_pet_path(@pet.id),  class: "btn btn-outline-secondary" %>
                <% end %>
          </tr>
        </thead>
      </table>
    </div>
  </div>
</div>