config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #admin側
  namespace :admin do
    get '/' => 'genres#index'
    # get 'about' => 'homes#about'
    resources :genres
  end

  #user側
  root to: 'homes#top'
  get '/' => 'homes#top'
  get 'about' => 'homes#about'

  resources :users, only: [:show, :edit, :update]
  get "user/:id/unsubscribe" => "users#unsubscribe", as: 'user_unsubscribe'
  patch 'user/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'

  resources :rooms, only: [:index, :create, :show]
  resources :genres
  resources :pets do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "search" => "pets#search"

  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries

  attachment :profile_image
  attachment :image

  has_many :relationships, foreign_key: "follower_id", class_name: "Relationship",
                           dependent: :destroy
  has_many :followings, through: :relationships, source: :following
  has_many :reverse_of_relationships, foreign_key: "following_id", class_name: "Relationship",
                                      dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :last_name, presence: true
  validates :first_name, presence: true
  VALID_KANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/.freeze
  validates :last_name_kana, presence: true, format: { with: VALID_KANA_REGEX }
  validates :first_name_kana, presence: true, format: { with: VALID_KANA_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :zipcode, presence: true
  validates :address, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/.freeze
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(following_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = relationships.find_by(following_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def full_name
    last_name + first_name
  end
  
  def self.guest
    find_or_create_by!(last_name: 'テスト',
    first_name: 'テスト',
    last_name_kana: 'テスト',
    first_name_kana: 'テスト',
    zipcode: '6666666',
    address: '東京都1-1-1',
    phone_number: '0900000000',
    email: 'test@example.com'
    ) do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  
  before_action :check_guest, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  before_action :check_guest, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (
        @user.active_for_authentication? == false
      )
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @pets = @user.pets.page(params[:page]).per(1)
    @comment = Comment.new
    @comments = Comment.all

    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end

      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = current_user.id
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '変更内容を更新しました。'
    else
      render :edit
    end
  end

  # 退会処理
  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    if @user.update(is_deleted: true)
      reset_session
      redirect_to root_path
    end
  end

  def followings
    # @userがフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    # @userをフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.followers
    @pet = @user.pets
  end

  private

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(@user.id)
    end
  end

  def user_params
    params.require(:user).permit(
      :last_name, :first_name,
      :last_name_kana, :first_name_kana,
      :email, :zipcode, :address, :phone_number,
      :profile_image, :introduction, :followers, :follower
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-12">
      <div class="background">
        <h2 class="heading">登録情報編集</h2>
        <%= render 'layouts/error_messages', model: @user %>
        <%= form_with model: @user, url: user_path(@user.id), method: :put, local: true do |f| %>
          <table class="table table-borderless">
            <tr>
              <th width="40%"><label for="profile_image__input">プロフィール画像</label></th>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image_icon.jpg", class: "rounded-circle" %></td>
              <td width="30%"> <%= f.attachment_field :profile_image %></td>
            </tr>
            <tr>
              <th>名前（姓）（名）</th>
              <td><%= f.text_field :last_name, autofocus: true, id: "last_name__input", class: "form-control" %></td>
              <td><%= f.text_field :first_name, autofocus: true, id: "first_name__input", class: "form-control" %></td>
            </tr>
            <tr>
              <th>フリガナ（セイ）（メイ）</th>
              <td><%= f.text_field :last_name_kana, autofocus: true, id: "last_name_kana__input", class: "form-control" %></td>
              <td><%= f.text_field :first_name_kana, autofocus: true, id: "first_name_kana__input", class: "form-control" %></td>
            </tr>
            <tr>
              <th><label for="mail_address__input">メールアドレス</label></th>
              <td colspan="2"><%= f.email_field :email, autofocus: true, id: "mail_address__input", class: "form-control" %></td>
            </tr>
            <tr>
              <th><label for="post_code__input">郵便番号（ハイフンなし）</label></th>
              <td colspan="2"><%= f.text_field :zipcode, autofocus: true, id: "post_code__input", class: "form-control" %></td>
            </tr>
            <tr>
              <th><label for="address__input">住所</label></th>
              <td colspan="2"><%= f.text_field :address, autofocus: true, id: "address__input", class: "form-control" %></td>
            </tr>
            <tr>
              <th><label for="phone_number__input">電話番号（ハイフンなし）</label></th>
              <td colspan="2"><%= f.text_field :phone_number, autofocus: true, id: "phone_number__input", class: "form-control" %></td>
            </tr>
            <tr>
              <th><label for="introduction__input">ひとこと (50文字以内)</label></th>
              <td colspan="2"><%= f.text_area :introduction, autocomplete: "introduction", class: "form-control" %></td>
            </tr>
            <tr>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "編集内容を保存する", class: "btn btn-secondary" %></td>
              <td><%= link_to '退会する', user_unsubscribe_path(@user.id), class: "btn btn-danger" %></td>
            </tr>
            <tr>
              <td></td>
            </tr>
          </table>
       
                  
                  
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-12">
      <div class="background">
        <h2 class="heading">Follower Users</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>プロフィール画像</th>
              <th>名前</th>
              <th>フォロー数</th>
              <th>フォロワー数</th>
            </tr>
          </thead>
          <tbody>
            <% @user.followers.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: '60x60', fallback: "no_image_icon.jpg", class: "rounded-circle" %></td>
              <td><%= link_to user_path(user.id) do %>
                    <%= user.full_name %>
                  <% end %></td>
              <td><%= user.followings.count %></td>
              <td><%= user.followers.count %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-12">
      <div class="background">
        <h2 class="heading">Follow Users</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>プロフィール画像</th>
              <th>名前</th>
              <th>フォロー数</th>
              <th>フォロワー数</th>
            </tr>
          </thead>
          <tbody>
            <% @user.followings.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: '60x60', fallback: "no_image_icon.jpg", class: "rounded-circle" %></td>
              <td><%= link_to user_path(user.id) do %>
                    <%= user.full_name %>
                  <% end %></td>
              <td><%= user.followings.count %></td>
              <td><%= user.followers.count %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-2">
      <% if @user == current_user %>
        <%= render 'pets/user', user: current_user %>
      <% else %>
        <%= render 'pets/user', user: @user %>
      <% end %>
    </div>

    <div class="col-md-9 offset-lg-1">
      <p id="notice"><%=  notice %></p>
      <div class="mypage">
      <% if @user == current_user %>
        <h2 class="heading">マイページ</h2>
      <% else %>
        <h2 class="heading">ユーザー詳細</h2>
      <% end %>

      <% @pets.each do |pet| %>
        <div class="p-list">
          <%= link_to pet_path(pet.id) do %>
            <% pet.pet_images.first(1).each do |image| %>
             <%= attachment_image_tag image, :image, format: "jpeg", size: '350x350', class: "rounded" %>
             <% end %>
          <% end %>
          <p class="pet-name">お名前:
            <%= link_to pet_path(pet.id) do %>
              <%= pet.name %></p>
            <% end %>
            <p>性別: <%= pet.gender %></p>
            <p>お誕生日: <%= pet.birthday %></p>
        </div>
      </div>
        <div class="favorite-btn<%= pet.id %>">
          <%= render 'favorites/favorite', pet: pet %>
        </div>
        <div class="comments_<%= pet.id %>">
          <%= render 'comments/comment', pet: pet, comment: @comment %>
        </div>
      <% end %>
     
      <%= paginate @pets %>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-12" align="center">
      <h2>本当に退会しますか？</h2>
        <p>退会する場合は、『退会する』をクリックしてください。</p>
          <%= link_to '退会しない', user_path(current_user.id), class: "btn btn-success" %>
          <% if user_signed_in? && @user.id == current_user.id %>
            <%= link_to "退会する", user_withdraw_path(current_user.id), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
          <% end %>
    </div>
  </div>
</div>