config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #admin側
  namespace :admin do
    get '/' => 'genres#index'
    # get 'about' => 'homes#about'
    resources :genres
  end

  #user側
  root to: 'homes#top'
  get '/' => 'homes#top'
  get 'about' => 'homes#about'

  resources :users, only: [:show, :edit, :update]
  get "user/:id/unsubscribe" => "users#unsubscribe", as: 'user_unsubscribe'
  patch 'user/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'

  resources :rooms, only: [:index, :create, :show]
  resources :genres
  resources :pets do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "search" => "pets#search"

  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :pets, dependent: :destroy

  validates :name, presence: true
  validates :is_active, inclusion: { in: [true, false] }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice:'ジャンルを追加しました。'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: '変更内容を更新しました。'
    else
      render :edit
    end
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path, notice: '投稿内容を削除しました。'
  end
  
  private
  def genre_params
   params.require(:genre).permit(:name, :is_active)
  end
 
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path, notice: 'ジャンルを追加しました。'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genres_path, notice: '変更内容を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path, notice: '投稿内容を削除しました。'
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9 mx-auto">
      <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :put, local: true do |f| %>
        <table class="table table-borderless">
            <tr>
                <td><%= f.label :"ジャンル" %></td>
                <td><%= f.text_field :name, class: "form-control" %></td>
            </tr>
            <tr>
                <td><%= f.radio_button :is_active, true %>取り扱い中
                    <%= f.radio_button :is_active, false %>現在取り扱っておりません</td>
            </tr>
            <tr>
                <td><%= f.submit "更新する", class: "btn btn-secondary" %></td>
            </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-9 offset-lg-1">
      <p id="notice"><%=  notice %></p>
      <%= render 'layouts/error_messages', model: @genre %>
      <%= form_with model: @genre, url: genres_path, local: true do |f| %>
        <table class="table table-borderless">
          <tr>
            <td></td>
            <td><%= f.label :"ジャンル" %></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td><%= f.radio_button :is_active, true %>取り扱い中
                <%= f.radio_button :is_active, false %>現在取り扱っておりません</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td><%= f.submit "追加", class: "btn btn-secondary ml-3 mt-3" %></td>
          </tr>
        </table>
      <% end %>
  
      <table class="table table-bordered text-center mt-5">
        <thead class='thead-light'>
          <tr class="table-name">
            <th>ジャンル</th>
            <th>状態</th>
            <th></th>
          </tr>
        </thead>
        <tbody style="padding-bottom: 100px">
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><% if genre.is_active == true %>
                  取り扱い中
                  <% elsif genre.is_active == false %>
                  現在取り扱っておりません
                  <% end %>
              </td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-secondary" %>
                  <%= link_to "削除する", admin_genre_path(genre.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>